export const WORKSPACES = [
  {
    id: 'system-body',
    label: 'Topology Cognition',
    eyebrow: 'Topology View',
    description: 'Operational topology cognition state and structural coherence context.',
  },
  {
    id: 'drift-timeline',
    label: 'Drift Timeline',
    eyebrow: 'Temporal View',
    description: 'Trajectory of structural distance from stable baseline.',
  },
  {
    id: 'evidence-console',
    label: 'Evidence Console',
    eyebrow: 'Evidence Lineage',
    description: 'Evidence lineage and operator-facing structural reasoning context.',
  },
  {
    id: 'data-connections',
    label: 'Data Connections',
    eyebrow: 'Signal Intake',
    description: 'Upload telemetry files and manage the live intake endpoint.',
  },
  {
    id: 'historical-replay',
    label: 'Structural Replay',
    eyebrow: 'Replay Fidelity',
    description: 'Scrub structural evolution, propagation pathways, and evidence lineage over time.',
  },
  {
    id: 'fleet-view',
    label: 'Multi-Site Cognition',
    eyebrow: 'Cognition Network',
    description: 'Cross-site structural cognition network and recurring archetype clusters.',
  },
  {
    id: 'structural-ontology',
    label: 'Structural Ontology',
    eyebrow: 'Ontology View',
    description: 'Visualize archetype primitives, ontology relationships, and domain cognition mappings.',
  },
  {
    id: 'ecosystem-workspace',
    label: 'Ecosystem Layer',
    eyebrow: 'SII Runtime',
    description: 'Read-only integration posture, cognition state export, and structural graph ecosystem context.',
  },
  {
    id: 'distributed-cognition',
    label: 'Distributed Cognition',
    eyebrow: 'Cognition Fabric',
    description: 'Federated structural cognition, persistent graph memory, ontology evolution, and governance.',
  },
  {
    id: 'operator-training',
    label: 'Operator Training',
    eyebrow: 'Cognition Training',
    description: 'Replay-backed operator cognition training for structural evolution interpretation.',
  },
  {
    id: 'behavior-science',
    label: 'Behavior Science',
    eyebrow: 'Research Layer',
    description: 'Long-horizon structural behavior science, taxonomy, evolution theory, and explainability standards.',
  },
  {
    id: 'operator-cognition-training',
    label: 'Operator Curriculum',
    eyebrow: 'Training System',
    description: 'Replay-based operator cognition curriculum for structural interpretation exercises.',
  },
  {
    id: 'structural-cognition-research',
    label: 'Research Workspace',
    eyebrow: 'Framework Layer',
    description: 'Universal primitives, structural evolution mathematics, governance queue, archives, and reasoning traces.',
  },
];
