export const WORKSPACES = [
  {
    id: 'operator-workflow',
    label: 'Operator Workflow',
    eyebrow: 'Primary Flow',
    description: 'Canonical operator flow from cognition state through replay, evidence lineage, continuation, and convergence review.',
  },
  {
    id: 'cultivation-mission-control',
    label: 'Cultivation Mission Control',
    eyebrow: 'Cultivation Primary',
    description: 'Canonical cultivation structural cognition interface for facility state, replay, pathways, and convergence.',
  },
  {
    id: 'cultivation-evidence',
    label: 'Cultivation Evidence',
    eyebrow: 'Cultivation Evidence',
    description: 'Evidence-first cultivation workspace for VPD relationships, compensation masking, and room synchronization drift.',
  },
  {
    id: 'historical-replay',
    label: 'Structural Replay',
    eyebrow: 'Replay First',
    description: 'Timeline scrub, propagation pathways, evidence by frame, and continuation windows.',
  },
  {
    id: 'evidence-console',
    label: 'Evidence Lineage',
    eyebrow: 'Evidence First',
    description: 'Inspect why structural cognition outputs are supported by subsystem and topology evidence.',
  },
  {
    id: 'system-body',
    label: 'Current Cognition State',
    eyebrow: 'State View',
    description: 'Facility cognition state, structural stability, and active pathways.',
  },
  {
    id: 'data-connections',
    label: 'Data Connections',
    eyebrow: 'Signal Intake',
    description: 'Upload telemetry files and manage the live intake endpoint.',
  },
  {
    id: 'fleet-view',
    label: 'Multi-Site Cognition',
    eyebrow: 'Expert View',
    description: 'Cross-site structural cognition network and recurring archetype clusters.',
  },
  {
    id: 'structural-ontology',
    label: 'Structural Ontology',
    eyebrow: 'Expert View',
    description: 'Visualize archetype primitives, ontology relationships, and domain cognition mappings.',
  },
  {
    id: 'ecosystem-workspace',
    label: 'Ecosystem Layer',
    eyebrow: 'Expert View',
    description: 'Read-only integration posture, cognition state export, and structural graph ecosystem context.',
  },
  {
    id: 'distributed-cognition',
    label: 'Distributed Cognition',
    eyebrow: 'Expert View',
    description: 'Federated structural cognition, persistent graph memory, ontology evolution, and governance.',
  },
  {
    id: 'operator-training',
    label: 'Operator Training',
    eyebrow: 'Cognition Training',
    description: 'Replay-backed operator cognition training for structural evolution interpretation.',
  },
  {
    id: 'behavior-science',
    label: 'Behavior Science',
    eyebrow: 'Research Layer',
    description: 'Long-horizon structural behavior science, taxonomy, evolution theory, and explainability standards.',
  },
  {
    id: 'operator-cognition-training',
    label: 'Operator Curriculum',
    eyebrow: 'Training System',
    description: 'Replay-based operator cognition curriculum for structural interpretation exercises.',
  },
  {
    id: 'structural-cognition-research',
    label: 'Research Workspace',
    eyebrow: 'Framework Layer',
    description: 'Universal primitives, structural evolution mathematics, governance queue, archives, and reasoning traces.',
  },
];
