-- Runtime schema v1. Mirrors the SQLite runtime contracts at main 011bda9c (including governance lifecycle events).
-- Dedicated schema avoids collisions with auth and production telemetry tables.

CREATE FUNCTION reject_runtime_mutation() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
    RAISE EXCEPTION '%', TG_ARGV[0] USING ERRCODE = '23514';
END;
$$;

CREATE TABLE upload_jobs (
                job_id TEXT PRIMARY KEY,
                status TEXT NOT NULL,
                started_at TEXT,
                completed_at TEXT,
                updated_at TEXT NOT NULL,
                payload_json TEXT NOT NULL
            );

CREATE TABLE upload_queue (
                job_id TEXT PRIMARY KEY,
                status TEXT NOT NULL CHECK (status IN ('pending', 'processing', 'completed', 'failed')),
                attempts BIGINT NOT NULL DEFAULT 0 CHECK (attempts >= 0),
                last_error TEXT,
                created_at TEXT NOT NULL,
                updated_at TEXT NOT NULL,
                locked_at TEXT,
                FOREIGN KEY(job_id) REFERENCES upload_jobs(job_id) ON DELETE CASCADE
            );

CREATE TABLE evidence_runs (
                run_id TEXT PRIMARY KEY,
                created_at TEXT NOT NULL,
                completed_at TEXT,
                status TEXT NOT NULL,
                source_name TEXT,
                scope_storage_id TEXT,
                payload_json TEXT NOT NULL
            );

CREATE TABLE operator_feedback_events (
                event_id TEXT PRIMARY KEY,
                run_id TEXT NOT NULL,
                recorded_at TEXT NOT NULL,
                actor TEXT NOT NULL,
                category TEXT NOT NULL,
                payload_json TEXT NOT NULL CHECK ((payload_json::json IS NOT NULL)),
                FOREIGN KEY(run_id) REFERENCES evidence_runs(run_id) ON DELETE CASCADE
            );

CREATE TABLE finding_status_events (
                event_id TEXT PRIMARY KEY,
                run_id TEXT NOT NULL,
                recorded_at TEXT NOT NULL,
                actor TEXT NOT NULL,
                state TEXT NOT NULL CHECK (state IN ('open', 'acknowledged', 'investigating', 'monitoring', 'resolved', 'dismissed')),
                payload_json TEXT NOT NULL CHECK ((payload_json::json IS NOT NULL)),
                FOREIGN KEY(run_id) REFERENCES evidence_runs(run_id) ON DELETE CASCADE
            );

CREATE TABLE finding_cases (
                finding_id TEXT PRIMARY KEY,
                source_kind TEXT NOT NULL CHECK (source_kind IN ('evidence_run', 'live_finding')),
                source_id TEXT NOT NULL,
                source_finding_key TEXT NOT NULL,
                scope_storage_id TEXT,
                dataset_scope_json TEXT CHECK (dataset_scope_json IS NULL OR (dataset_scope_json::json IS NOT NULL)),
                source_snapshot_json TEXT NOT NULL CHECK ((source_snapshot_json::json IS NOT NULL)),
                created_at TEXT NOT NULL,
                UNIQUE (source_kind, source_id, source_finding_key)
            );

CREATE TABLE evidence_audit_tag_events (
                event_id TEXT PRIMARY KEY,
                run_id TEXT NOT NULL,
                recorded_at TEXT NOT NULL,
                actor TEXT NOT NULL,
                payload_json TEXT NOT NULL CHECK ((payload_json::json IS NOT NULL)),
                FOREIGN KEY(run_id) REFERENCES evidence_runs(run_id) ON DELETE CASCADE
            );

CREATE TABLE audit_events (
                event_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                created_at TEXT NOT NULL,
                request_id TEXT,
                actor TEXT,
                action TEXT NOT NULL,
                resource_type TEXT NOT NULL,
                resource_id TEXT,
                detail_json TEXT NOT NULL
            );

CREATE TABLE latest_payloads (
                key TEXT PRIMARY KEY,
                updated_at TEXT NOT NULL,
                payload_json TEXT NOT NULL
            );

CREATE TABLE data_connections (
                connection_id TEXT PRIMARY KEY,
                name TEXT NOT NULL,
                status TEXT NOT NULL CHECK (status IN ('offline', 'polling', 'online', 'ready', 'error', 'not_configured')),
                polling_enabled BIGINT NOT NULL DEFAULT 0 CHECK (polling_enabled IN (0, 1)),
                updated_at TEXT NOT NULL,
                payload_json TEXT NOT NULL CHECK ((payload_json::json IS NOT NULL))
            );

CREATE TABLE auth_users (
                email TEXT PRIMARY KEY,
                name TEXT NOT NULL,
                role TEXT NOT NULL CHECK (role IN ('viewer', 'operator', 'admin')),
                salt TEXT NOT NULL,
                password_hash TEXT NOT NULL,
                created_at TEXT NOT NULL,
                updated_at TEXT NOT NULL,
                last_login_at TEXT,
                is_active BIGINT NOT NULL DEFAULT 1 CHECK (is_active IN (0, 1)),
                deactivated_at TEXT,
                bootstrap_managed BIGINT NOT NULL DEFAULT 0 CHECK (bootstrap_managed IN (0, 1))
            );

CREATE TABLE auth_sessions (
                session_id TEXT PRIMARY KEY,
                email TEXT NOT NULL,
                created_at TEXT NOT NULL,
                expires_at TEXT NOT NULL,
                last_seen_at TEXT,
                revoked_at TEXT,
                FOREIGN KEY(email) REFERENCES auth_users(email) ON DELETE CASCADE
            );

CREATE TABLE runtime_schema_migrations (
            migration_id TEXT PRIMARY KEY,
            applied_at TEXT NOT NULL
        );

CREATE TABLE telemetry_ingestion_batches (
                batch_id TEXT PRIMARY KEY,
                system_id TEXT NOT NULL,
                source TEXT NOT NULL,
                received_at TEXT NOT NULL,
                completed_at TEXT,
                result_json TEXT CHECK (result_json IS NULL OR (result_json::json IS NOT NULL))
            );

CREATE TABLE telemetry_signal_mappings (
                mapping_id TEXT PRIMARY KEY,
                system_id TEXT NOT NULL,
                source_tag TEXT NOT NULL,
                canonical_signal TEXT NOT NULL,
                unit TEXT,
                enabled BIGINT NOT NULL DEFAULT 1 CHECK (enabled IN (0, 1)),
                created_at TEXT NOT NULL,
                updated_at TEXT NOT NULL,
                UNIQUE (system_id, source_tag)
            );

CREATE TABLE normalized_telemetry (
                telemetry_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                system_id TEXT NOT NULL,
                canonical_signal TEXT NOT NULL,
                telemetry_timestamp TEXT NOT NULL,
                value DOUBLE PRECISION NOT NULL CHECK (
                    value = value
                    AND value <= 1.7976931348623157e308
                    AND value >= -1.7976931348623157e308
                ),
                source TEXT NOT NULL,
                source_tag TEXT NOT NULL,
                quality_status TEXT NOT NULL CHECK (quality_status IN ('good', 'out_of_order')),
                ingested_at TEXT NOT NULL,
                batch_id TEXT NOT NULL,
                FOREIGN KEY(batch_id) REFERENCES telemetry_ingestion_batches(batch_id),
                UNIQUE (system_id, canonical_signal, telemetry_timestamp, source)
            );

CREATE TABLE rejected_telemetry (
                rejection_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                batch_id TEXT NOT NULL,
                system_id TEXT NOT NULL,
                source TEXT NOT NULL,
                source_tag TEXT,
                telemetry_timestamp TEXT,
                submitted_value_json TEXT CHECK (
                    submitted_value_json IS NULL OR (submitted_value_json::json IS NOT NULL)
                ),
                rejection_reason TEXT NOT NULL CHECK (rejection_reason IN (
                    'missing_timestamp',
                    'invalid_timestamp',
                    'future_timestamp',
                    'non_numeric_value',
                    'nan_value',
                    'infinite_value',
                    'unmapped_signal',
                    'duplicate_record',
                    'out_of_order_record'
                )),
                ingested_at TEXT NOT NULL,
                FOREIGN KEY(batch_id) REFERENCES telemetry_ingestion_batches(batch_id)
            );

CREATE TABLE telemetry_ingestion_health (
                system_id TEXT NOT NULL,
                source TEXT NOT NULL,
                last_successful_ingestion_at TEXT,
                last_telemetry_timestamp TEXT,
                accepted_count BIGINT NOT NULL DEFAULT 0 CHECK (accepted_count >= 0),
                rejected_count BIGINT NOT NULL DEFAULT 0 CHECK (rejected_count >= 0),
                latest_error_or_warning TEXT,
                status TEXT NOT NULL CHECK (status IN ('healthy', 'delayed', 'error', 'never_received')),
                updated_at TEXT NOT NULL,
                PRIMARY KEY (system_id, source)
            );

CREATE TABLE finding_workflow_events (
                    event_id TEXT PRIMARY KEY,
                    finding_id TEXT NOT NULL,
                    version BIGINT NOT NULL CHECK (version > 0),
                    event_type TEXT NOT NULL CHECK (event_type IN (
                        'workflow_updated', 'feedback_recorded', 'resolution_recorded',
                        'legacy_status_imported', 'legacy_feedback_imported',
                        'field_report_recorded', 'governance_lifecycle_recorded'
                    )),
                    recorded_at TEXT NOT NULL,
                    actor TEXT NOT NULL,
                    idempotency_key TEXT,
                    payload_json TEXT NOT NULL CHECK ((payload_json::json IS NOT NULL)),
                    FOREIGN KEY(finding_id) REFERENCES finding_cases(finding_id) ON DELETE RESTRICT,
                    UNIQUE (finding_id, version),
                    UNIQUE (finding_id, idempotency_key)
                );

CREATE TABLE "live_analysis_configurations" (
                system_id TEXT NOT NULL,
                scope_storage_id TEXT,
                enabled BIGINT NOT NULL DEFAULT 0 CHECK (enabled IN (0, 1)),
                approved_baseline_id TEXT,
                analysis_interval_seconds BIGINT NOT NULL DEFAULT 300 CHECK (analysis_interval_seconds > 0),
                comparison_window_minutes BIGINT NOT NULL DEFAULT 60 CHECK (comparison_window_minutes > 0),
                minimum_coverage_percent DOUBLE PRECISION NOT NULL DEFAULT 80 CHECK (
                    minimum_coverage_percent >= 0 AND minimum_coverage_percent <= 100
                ),
                allowed_lateness_minutes BIGINT NOT NULL DEFAULT 5 CHECK (allowed_lateness_minutes >= 0),
                last_analysis_started_at TEXT,
                last_analysis_completed_at TEXT,
                next_analysis_at TEXT,
                current_status TEXT NOT NULL DEFAULT 'disabled' CHECK (
                    current_status IN ('enabled', 'disabled', 'running', 'waiting', 'error')
                ),
                latest_error TEXT,
                created_at TEXT NOT NULL,
                updated_at TEXT NOT NULL,
                UNIQUE(scope_storage_id, system_id)
            );

CREATE TABLE "live_analysis_runs" (
                run_id TEXT PRIMARY KEY,
                scope_storage_id TEXT,
                system_id TEXT NOT NULL,
                baseline_reference TEXT NOT NULL DEFAULT '',
                window_start TEXT NOT NULL,
                window_end TEXT NOT NULL,
                status TEXT NOT NULL CHECK (status IN ('pending', 'running', 'completed', 'skipped', 'failed')),
                started_at TEXT,
                completed_at TEXT,
                rows_analyzed BIGINT NOT NULL DEFAULT 0 CHECK (rows_analyzed >= 0),
                signals_analyzed BIGINT NOT NULL DEFAULT 0 CHECK (signals_analyzed >= 0),
                coverage DOUBLE PRECISION NOT NULL DEFAULT 0 CHECK (coverage >= 0 AND coverage <= 100),
                skipped_reason TEXT CHECK (skipped_reason IS NULL OR skipped_reason IN (
                    'disabled', 'missing_baseline', 'insufficient_coverage',
                    'insufficient_signals', 'telemetry_delayed', 'telemetry_unavailable',
                    'duplicate_window', 'analysis_already_running'
                )),
                error_summary TEXT,
                analytics_result_reference TEXT,
                analytics_result_json TEXT CHECK (
                    analytics_result_json IS NULL OR (analytics_result_json::json IS NOT NULL)
                ),
                created_findings_count BIGINT NOT NULL DEFAULT 0 CHECK (created_findings_count >= 0),
                updated_findings_count BIGINT NOT NULL DEFAULT 0 CHECK (updated_findings_count >= 0),
                resolved_findings_count BIGINT NOT NULL DEFAULT 0 CHECK (resolved_findings_count >= 0),
                created_at TEXT NOT NULL,
                UNIQUE(scope_storage_id, run_id),
                UNIQUE(scope_storage_id, system_id, baseline_reference, window_start, window_end)
            );

CREATE TABLE "live_findings" (
                finding_id TEXT PRIMARY KEY,
                scope_storage_id TEXT,
                deduplication_key TEXT NOT NULL,
                system_id TEXT NOT NULL,
                relationship_identity TEXT NOT NULL,
                finding_classification_json TEXT NOT NULL CHECK ((finding_classification_json::json IS NOT NULL)),
                first_detected_at TEXT NOT NULL,
                last_observed_at TEXT NOT NULL,
                opened_at TEXT,
                resolved_at TEXT,
                current_state TEXT NOT NULL CHECK (current_state IN ('observing', 'open', 'resolved')),
                persistence_state_json TEXT NOT NULL CHECK ((persistence_state_json::json IS NOT NULL)),
                severity_score DOUBLE PRECISION,
                latest_evidence_json TEXT NOT NULL CHECK ((latest_evidence_json::json IS NOT NULL)),
                source_live_analysis_run_id TEXT NOT NULL,
                baseline_reference TEXT NOT NULL,
                created_at TEXT NOT NULL,
                updated_at TEXT NOT NULL,
                UNIQUE(scope_storage_id, deduplication_key),
                FOREIGN KEY(scope_storage_id, source_live_analysis_run_id)
                    REFERENCES "live_analysis_runs"(scope_storage_id, run_id)
            );

CREATE TABLE "live_analysis_health" (
                system_id TEXT NOT NULL,
                scope_storage_id TEXT,
                last_attempted_run_at TEXT,
                last_completed_run_at TEXT,
                last_successful_run_at TEXT,
                current_status TEXT NOT NULL CHECK (current_status IN (
                    'healthy', 'waiting_for_data', 'missing_baseline', 'delayed',
                    'running', 'error', 'disabled', 'never_run'
                )),
                current_window_coverage DOUBLE PRECISION NOT NULL DEFAULT 0 CHECK (
                    current_window_coverage >= 0 AND current_window_coverage <= 100
                ),
                latest_skipped_reason TEXT,
                consecutive_failures BIGINT NOT NULL DEFAULT 0 CHECK (consecutive_failures >= 0),
                latest_error TEXT,
                next_scheduled_run TEXT,
                updated_at TEXT NOT NULL,
                UNIQUE(scope_storage_id, system_id)
            );

CREATE TABLE upload_queue_routing (
                job_id TEXT PRIMARY KEY,
                routing_json TEXT NOT NULL CHECK ((routing_json::json IS NOT NULL)),
                created_at TEXT NOT NULL,
                FOREIGN KEY(job_id) REFERENCES upload_queue(job_id) ON DELETE CASCADE
            );

CREATE TABLE validated_outcomes (
                outcome_revision_id TEXT PRIMARY KEY,
                outcome_id TEXT NOT NULL,
                revision BIGINT NOT NULL CHECK (revision > 0),
                supersedes_revision_id TEXT,
                scope_storage_id TEXT NOT NULL CHECK (length(trim(scope_storage_id)) > 0),
                tenant_id TEXT NOT NULL CHECK (length(trim(tenant_id)) > 0),
                facility_id TEXT NOT NULL CHECK (length(trim(facility_id)) > 0),
                system_id TEXT NOT NULL CHECK (length(trim(system_id)) > 0),
                asset_equipment_id TEXT,
                outcome_schema_version TEXT NOT NULL,
                outcome_type TEXT NOT NULL CHECK (outcome_type IN (
                    'confirmed_maintenance_event', 'inspection_result',
                    'confirmed_fault', 'confirmed_degraded_condition', 'repair',
                    'component_replacement', 'operator_confirmed_explanation',
                    'return_toward_expected_behavior',
                    'expected_no_fault_confirmation', 'false_positive_not_useful',
                    'stable_operation_observation'
                )),
                outcome_family TEXT NOT NULL CHECK (outcome_family IN (
                    'degradation_or_fault', 'inspection_confirmation',
                    'maintenance_or_intervention', 'repair_or_replacement',
                    'recovery', 'expected_or_no_fault',
                    'not_useful_or_false_positive', 'validated_explanation'
                )),
                health_disposition TEXT NOT NULL CHECK (health_disposition IN (
                    'degraded', 'fault_confirmed', 'expected_behavior', 'no_fault',
                    'not_useful', 'explained', 'intervention_recorded',
                    'recovery_observed', 'unrelated_maintenance',
                    'no_observed_behavior_change', 'stable_observation',
                    'indeterminate'
                )),
                validation_status TEXT NOT NULL CHECK (validation_status IN (
                    'pending', 'validated', 'rejected', 'retracted', 'superseded'
                )),
                occurred_start_at TEXT NOT NULL,
                occurred_end_at TEXT NOT NULL,
                windows_json TEXT CHECK (
                    windows_json IS NULL OR (
                        (windows_json::json IS NOT NULL) AND json_typeof(windows_json::json) = 'object'
                    )
                ),
                source_category TEXT NOT NULL,
                source_system TEXT,
                source_record_id TEXT,
                source_record_version TEXT,
                source_recorded_at TEXT,
                source_identity_hash TEXT,
                reported_by TEXT NOT NULL,
                reported_at TEXT NOT NULL,
                validated_by TEXT,
                validated_at TEXT,
                validation_basis_json TEXT NOT NULL CHECK (
                    (validation_basis_json::json IS NOT NULL)
                    AND json_typeof(validation_basis_json::json) = 'object'
                ),
                provenance_categories_json TEXT NOT NULL CHECK (
                    (provenance_categories_json::json IS NOT NULL)
                    AND json_typeof(provenance_categories_json::json) = 'array'
                ),
                authority_tier TEXT NOT NULL CHECK (authority_tier IN ('A', 'B', 'C', 'D')),
                reliability_class TEXT NOT NULL,
                reliability_basis_json TEXT NOT NULL CHECK (
                    (reliability_basis_json::json IS NOT NULL)
                    AND json_typeof(reliability_basis_json::json) = 'object'
                ),
                canonical_incident_key TEXT,
                dedup_status TEXT NOT NULL CHECK (dedup_status IN (
                    'canonical', 'confirmed_distinct', 'possible_duplicate',
                    'confirmed_duplicate', 'unadjudicated'
                )),
                possible_duplicate_of_json TEXT NOT NULL DEFAULT '[]' CHECK (
                    (possible_duplicate_of_json::json IS NOT NULL)
                    AND json_typeof(possible_duplicate_of_json::json) = 'array'
                ),
                dedup_basis_json TEXT NOT NULL CHECK (
                    (dedup_basis_json::json IS NOT NULL)
                    AND json_typeof(dedup_basis_json::json) = 'object'
                ),
                observation_protocol_json TEXT CHECK (
                    observation_protocol_json IS NULL OR (
                        (observation_protocol_json::json IS NOT NULL)
                        AND json_typeof(observation_protocol_json::json) = 'object'
                    )
                ),
                structured_metadata_json TEXT NOT NULL CHECK (
                    (structured_metadata_json::json IS NOT NULL)
                    AND json_typeof(structured_metadata_json::json) = 'object'
                ),
                metadata_schema_version TEXT NOT NULL,
                actor TEXT NOT NULL,
                recorded_at TEXT NOT NULL,
                idempotency_key TEXT,
                request_fingerprint TEXT,
                UNIQUE(scope_storage_id, tenant_id, facility_id, system_id, outcome_id, revision),
                UNIQUE(scope_storage_id, tenant_id, facility_id, system_id, outcome_id, outcome_revision_id),
                FOREIGN KEY(
                    scope_storage_id, tenant_id, facility_id, system_id,
                    outcome_id, supersedes_revision_id
                ) REFERENCES validated_outcomes(
                    scope_storage_id, tenant_id, facility_id, system_id,
                    outcome_id, outcome_revision_id
                ) ON DELETE RESTRICT,
                CHECK (occurred_end_at >= occurred_start_at),
                CHECK (
                    (revision = 1 AND supersedes_revision_id IS NULL)
                    OR (revision > 1 AND supersedes_revision_id IS NOT NULL)
                ),
                CHECK (
                    (validation_status = 'pending' AND validated_by IS NULL AND validated_at IS NULL)
                    OR (validation_status <> 'pending' AND validated_by IS NOT NULL AND validated_at IS NOT NULL)
                ),
                CHECK (
                    outcome_type <> 'stable_operation_observation'
                    OR observation_protocol_json IS NOT NULL
                ),
                CHECK (idempotency_key IS NULL OR request_fingerprint IS NOT NULL)
            );

CREATE TABLE validated_outcome_links (
                link_revision_id TEXT PRIMARY KEY,
                link_id TEXT NOT NULL,
                revision BIGINT NOT NULL CHECK (revision > 0),
                supersedes_revision_id TEXT,
                outcome_id TEXT NOT NULL,
                outcome_revision_id TEXT NOT NULL,
                scope_storage_id TEXT NOT NULL CHECK (length(trim(scope_storage_id)) > 0),
                tenant_id TEXT NOT NULL CHECK (length(trim(tenant_id)) > 0),
                facility_id TEXT NOT NULL CHECK (length(trim(facility_id)) > 0),
                system_id TEXT NOT NULL CHECK (length(trim(system_id)) > 0),
                asset_equipment_id TEXT,
                finding_id TEXT,
                evidence_run_id TEXT,
                evidence_package_id TEXT,
                evidence_package_revision BIGINT CHECK (
                    evidence_package_revision IS NULL OR evidence_package_revision > 0
                ),
                evidence_content_hash TEXT,
                subject_type TEXT NOT NULL CHECK (subject_type IN (
                    'signal', 'relationship', 'asset_equipment', 'subsystem'
                )),
                subject_id TEXT NOT NULL,
                subject_mapping_version TEXT NOT NULL,
                behavioral_model_id TEXT,
                behavioral_model_version TEXT,
                behavioral_snapshot_id TEXT,
                baseline_reference_id TEXT,
                baseline_reference_version TEXT,
                telemetry_schema_fingerprint TEXT,
                system_configuration_fingerprint TEXT,
                compatibility_epoch TEXT,
                context_schema_version TEXT NOT NULL,
                context_json TEXT NOT NULL CHECK (
                    (context_json::json IS NOT NULL) AND json_typeof(context_json::json) = 'object'
                ),
                context_fingerprint TEXT NOT NULL,
                context_episode_id TEXT NOT NULL,
                context_source_refs_json TEXT NOT NULL CHECK (
                    (context_source_refs_json::json IS NOT NULL)
                    AND json_typeof(context_source_refs_json::json) = 'array'
                ),
                temporal_role TEXT NOT NULL CHECK (temporal_role IN (
                    'pre_outcome', 'outcome_period', 'post_intervention',
                    'recovery', 'stable_comparison'
                )),
                window_start_at TEXT NOT NULL,
                window_end_at TEXT NOT NULL,
                link_origin TEXT NOT NULL CHECK (link_origin IN (
                    'direct_source', 'human_reviewed', 'deterministic_reference'
                )),
                link_confidence TEXT NOT NULL CHECK (link_confidence IN (
                    'direct', 'reviewed', 'limited'
                )),
                link_basis_json TEXT NOT NULL CHECK (
                    (link_basis_json::json IS NOT NULL) AND json_typeof(link_basis_json::json) = 'object'
                ),
                linked_by TEXT NOT NULL,
                linked_at TEXT NOT NULL,
                retrospective_window_selection BIGINT NOT NULL DEFAULT 0 CHECK (
                    retrospective_window_selection IN (0, 1)
                ),
                subject_state TEXT NOT NULL CHECK (subject_state IN (
                    'active_changed', 'present_aligned', 'absent_evaluable', 'not_evaluable'
                )),
                observation_basis_json TEXT NOT NULL CHECK (
                    (observation_basis_json::json IS NOT NULL)
                    AND json_typeof(observation_basis_json::json) = 'object'
                ),
                link_status TEXT NOT NULL CHECK (link_status IN (
                    'pending', 'active', 'rejected', 'retracted', 'superseded'
                )),
                actor TEXT NOT NULL,
                recorded_at TEXT NOT NULL,
                idempotency_key TEXT,
                request_fingerprint TEXT,
                FOREIGN KEY(
                    scope_storage_id, tenant_id, facility_id, system_id,
                    outcome_id, outcome_revision_id
                ) REFERENCES validated_outcomes(
                    scope_storage_id, tenant_id, facility_id, system_id,
                    outcome_id, outcome_revision_id
                ) ON DELETE RESTRICT,
                UNIQUE(scope_storage_id, tenant_id, facility_id, system_id, link_id, revision),
                UNIQUE(scope_storage_id, tenant_id, facility_id, system_id, link_id, link_revision_id),
                FOREIGN KEY(
                    scope_storage_id, tenant_id, facility_id, system_id,
                    link_id, supersedes_revision_id
                ) REFERENCES validated_outcome_links(
                    scope_storage_id, tenant_id, facility_id, system_id,
                    link_id, link_revision_id
                ) ON DELETE RESTRICT,
                CHECK (window_end_at >= window_start_at),
                CHECK (
                    (revision = 1 AND supersedes_revision_id IS NULL)
                    OR (revision > 1 AND supersedes_revision_id IS NOT NULL)
                ),
                CHECK (
                    finding_id IS NOT NULL OR evidence_run_id IS NOT NULL
                    OR evidence_content_hash IS NOT NULL
                    OR behavioral_snapshot_id IS NOT NULL
                    OR baseline_reference_id IS NOT NULL
                ),
                CHECK (idempotency_key IS NULL OR request_fingerprint IS NOT NULL)
            );

CREATE TABLE health_relevance_versions (
                relevance_version_id TEXT PRIMARY KEY,
                state_key_hash TEXT NOT NULL,
                version BIGINT NOT NULL CHECK (version > 0),
                scope_storage_id TEXT NOT NULL CHECK (length(trim(scope_storage_id)) > 0),
                tenant_id TEXT NOT NULL CHECK (length(trim(tenant_id)) > 0),
                facility_id TEXT NOT NULL CHECK (length(trim(facility_id)) > 0),
                system_id TEXT NOT NULL CHECK (length(trim(system_id)) > 0),
                asset_equipment_id TEXT,
                subject_type TEXT NOT NULL CHECK (subject_type IN (
                    'signal', 'relationship', 'asset_equipment', 'subsystem'
                )),
                subject_id TEXT NOT NULL,
                subject_mapping_version TEXT NOT NULL,
                context_schema_version TEXT NOT NULL,
                context_json TEXT NOT NULL CHECK (
                    (context_json::json IS NOT NULL) AND json_typeof(context_json::json) = 'object'
                ),
                context_fingerprint TEXT NOT NULL,
                compatibility_epoch TEXT NOT NULL,
                method_class TEXT NOT NULL CHECK (method_class IN (
                    'bayesian_shrinkage_v1', 'outcome_conditioned_information_v1'
                )),
                method_version TEXT NOT NULL,
                method_config_version TEXT NOT NULL,
                input_snapshot_id TEXT NOT NULL,
                input_manifest_hash TEXT NOT NULL,
                outcome_watermark TEXT NOT NULL,
                link_watermark TEXT NOT NULL,
                previous_version_id TEXT,
                raw_outcome_count BIGINT NOT NULL CHECK (raw_outcome_count >= 0),
                eligible_outcome_count BIGINT NOT NULL CHECK (eligible_outcome_count >= 0),
                canonical_incident_count BIGINT NOT NULL CHECK (canonical_incident_count >= 0),
                recurrence_count BIGINT NOT NULL CHECK (recurrence_count >= 0),
                positive_count BIGINT NOT NULL CHECK (positive_count >= 0),
                negative_count BIGINT NOT NULL CHECK (negative_count >= 0),
                neutral_count BIGINT NOT NULL CHECK (neutral_count >= 0),
                comparison_window_count BIGINT NOT NULL CHECK (comparison_window_count >= 0),
                excluded_count BIGINT NOT NULL CHECK (excluded_count >= 0),
                duplicate_suppressed_count BIGINT NOT NULL CHECK (duplicate_suppressed_count >= 0),
                outcome_family_counts_json TEXT NOT NULL CHECK (
                    (outcome_family_counts_json::json IS NOT NULL)
                    AND json_typeof(outcome_family_counts_json::json) = 'object'
                ),
                context_metadata_completeness DOUBLE PRECISION NOT NULL CHECK (
                    context_metadata_completeness >= 0.0
                    AND context_metadata_completeness <= 1.0
                ),
                context_episode_count BIGINT NOT NULL CHECK (context_episode_count >= 0),
                protocol_completion DOUBLE PRECISION CHECK (
                    protocol_completion IS NULL
                    OR (protocol_completion >= 0.0 AND protocol_completion <= 1.0)
                ),
                temporal_consistency DOUBLE PRECISION CHECK (
                    temporal_consistency IS NULL
                    OR (temporal_consistency >= 0.0 AND temporal_consistency <= 1.0)
                ),
                tier_a_count BIGINT NOT NULL CHECK (tier_a_count >= 0),
                tier_b_count BIGINT NOT NULL CHECK (tier_b_count >= 0),
                tier_c_count BIGINT NOT NULL CHECK (tier_c_count >= 0),
                tier_d_count BIGINT NOT NULL CHECK (tier_d_count >= 0),
                independent_count BIGINT NOT NULL CHECK (independent_count >= 0),
                neraium_influenced_count BIGINT NOT NULL CHECK (neraium_influenced_count >= 0),
                same_actor_validation_count BIGINT NOT NULL CHECK (same_actor_validation_count >= 0),
                evidence_state TEXT NOT NULL CHECK (evidence_state IN (
                    'insufficient_outcome_evidence', 'emerging_relevance',
                    'supported_relevance', 'contradictory_evidence',
                    'not_supported_by_outcomes'
                )),
                evidence_direction TEXT NOT NULL CHECK (evidence_direction IN (
                    'positive_dominant', 'negative_dominant', 'mixed', 'indeterminate'
                )),
                state_reason_codes_json TEXT NOT NULL CHECK (
                    (state_reason_codes_json::json IS NOT NULL)
                    AND json_typeof(state_reason_codes_json::json) = 'array'
                ),
                freshness_status TEXT NOT NULL CHECK (freshness_status IN (
                    'current', 'stale', 'superseded_epoch'
                )),
                method_components_json TEXT NOT NULL CHECK (
                    (method_components_json::json IS NOT NULL)
                    AND json_typeof(method_components_json::json) = 'object'
                ),
                uncertainty_json TEXT NOT NULL CHECK (
                    (uncertainty_json::json IS NOT NULL) AND json_typeof(uncertainty_json::json) = 'object'
                ),
                outcome_schema_version TEXT NOT NULL,
                threshold_config_version TEXT NOT NULL,
                threshold_config_json TEXT NOT NULL CHECK (
                    (threshold_config_json::json IS NOT NULL)
                    AND json_typeof(threshold_config_json::json) = 'object'
                ),
                authority_rules_version TEXT NOT NULL,
                dedup_rules_version TEXT NOT NULL,
                compatibility_rules_version TEXT NOT NULL,
                configuration_hash TEXT NOT NULL,
                first_evidence_at TEXT,
                last_evidence_at TEXT,
                computed_at TEXT NOT NULL,
                created_by TEXT NOT NULL,
                code_build_version TEXT NOT NULL,
                UNIQUE(state_key_hash, version),
                UNIQUE(
                    scope_storage_id, tenant_id, facility_id, system_id,
                    relevance_version_id
                ),
                UNIQUE(
                    scope_storage_id, tenant_id, facility_id, system_id,
                    state_key_hash, relevance_version_id
                ),
                FOREIGN KEY(
                    scope_storage_id, tenant_id, facility_id, system_id,
                    state_key_hash, previous_version_id
                ) REFERENCES health_relevance_versions(
                    scope_storage_id, tenant_id, facility_id, system_id,
                    state_key_hash, relevance_version_id
                ) ON DELETE RESTRICT,
                CHECK (
                    (version = 1 AND previous_version_id IS NULL)
                    OR (version > 1 AND previous_version_id IS NOT NULL)
                ),
                CHECK (
                    (first_evidence_at IS NULL AND last_evidence_at IS NULL)
                    OR (first_evidence_at IS NOT NULL AND last_evidence_at IS NOT NULL
                        AND last_evidence_at >= first_evidence_at)
                )
            );

CREATE TABLE health_relevance_contributions (
                contribution_id TEXT PRIMARY KEY,
                relevance_version_id TEXT NOT NULL,
                outcome_id TEXT NOT NULL,
                outcome_revision_id TEXT NOT NULL,
                link_id TEXT NOT NULL,
                link_revision_id TEXT NOT NULL,
                scope_storage_id TEXT NOT NULL CHECK (length(trim(scope_storage_id)) > 0),
                tenant_id TEXT NOT NULL CHECK (length(trim(tenant_id)) > 0),
                facility_id TEXT NOT NULL CHECK (length(trim(facility_id)) > 0),
                system_id TEXT NOT NULL CHECK (length(trim(system_id)) > 0),
                asset_equipment_id TEXT,
                subject_type TEXT NOT NULL CHECK (subject_type IN (
                    'signal', 'relationship', 'asset_equipment', 'subsystem'
                )),
                subject_id TEXT NOT NULL,
                subject_mapping_version TEXT NOT NULL,
                context_fingerprint TEXT NOT NULL,
                compatibility_epoch TEXT NOT NULL,
                canonical_incident_key TEXT,
                outcome_family TEXT NOT NULL CHECK (outcome_family IN (
                    'degradation_or_fault', 'inspection_confirmation',
                    'maintenance_or_intervention', 'repair_or_replacement',
                    'recovery', 'expected_or_no_fault',
                    'not_useful_or_false_positive', 'validated_explanation'
                )),
                evidence_treatment TEXT NOT NULL CHECK (evidence_treatment IN (
                    'positive', 'negative', 'neutral', 'comparison',
                    'contradictory', 'excluded', 'duplicate_suppressed'
                )),
                subject_state TEXT NOT NULL CHECK (subject_state IN (
                    'active_changed', 'present_aligned', 'absent_evaluable', 'not_evaluable'
                )),
                temporal_role TEXT NOT NULL CHECK (temporal_role IN (
                    'pre_outcome', 'outcome_period', 'post_intervention',
                    'recovery', 'stable_comparison'
                )),
                authority_tier TEXT NOT NULL CHECK (authority_tier IN ('A', 'B', 'C', 'D')),
                provenance_categories_json TEXT NOT NULL CHECK (
                    (provenance_categories_json::json IS NOT NULL)
                    AND json_typeof(provenance_categories_json::json) = 'array'
                ),
                method_input_cell TEXT NOT NULL DEFAULT 'not_applicable',
                method_component_json TEXT NOT NULL CHECK (
                    (method_component_json::json IS NOT NULL)
                    AND json_typeof(method_component_json::json) = 'object'
                ),
                reason_code TEXT NOT NULL,
                finding_id TEXT,
                evidence_run_id TEXT,
                evidence_package_id TEXT,
                evidence_content_hash TEXT,
                behavioral_model_id TEXT,
                behavioral_model_version TEXT,
                behavioral_snapshot_id TEXT,
                baseline_reference_id TEXT,
                baseline_reference_version TEXT,
                telemetry_schema_fingerprint TEXT,
                system_configuration_fingerprint TEXT,
                input_manifest_hash TEXT NOT NULL,
                configuration_hash TEXT NOT NULL,
                created_by TEXT NOT NULL,
                created_at TEXT NOT NULL,
                FOREIGN KEY(
                    scope_storage_id, tenant_id, facility_id, system_id,
                    relevance_version_id
                ) REFERENCES health_relevance_versions(
                    scope_storage_id, tenant_id, facility_id, system_id,
                    relevance_version_id
                ) ON DELETE RESTRICT,
                FOREIGN KEY(
                    scope_storage_id, tenant_id, facility_id, system_id,
                    outcome_id, outcome_revision_id
                ) REFERENCES validated_outcomes(
                    scope_storage_id, tenant_id, facility_id, system_id,
                    outcome_id, outcome_revision_id
                ) ON DELETE RESTRICT,
                FOREIGN KEY(
                    scope_storage_id, tenant_id, facility_id, system_id,
                    link_id, link_revision_id
                ) REFERENCES validated_outcome_links(
                    scope_storage_id, tenant_id, facility_id, system_id,
                    link_id, link_revision_id
                ) ON DELETE RESTRICT,
                UNIQUE(
                    relevance_version_id, outcome_revision_id, link_revision_id,
                    evidence_treatment, method_input_cell
                )
            );

CREATE INDEX idx_upload_jobs_updated_at ON upload_jobs(updated_at DESC);

CREATE INDEX idx_upload_jobs_status_updated ON upload_jobs(status, updated_at DESC);

CREATE INDEX idx_upload_queue_status_created ON upload_queue(status, created_at ASC);

CREATE INDEX idx_upload_queue_updated_at ON upload_queue(updated_at DESC);

CREATE INDEX idx_upload_queue_status_updated ON upload_queue(status, updated_at ASC);

CREATE INDEX idx_evidence_runs_created_at ON evidence_runs(created_at DESC);

CREATE INDEX idx_evidence_runs_status_created ON evidence_runs(status, created_at DESC);

CREATE INDEX idx_feedback_events_run_time ON operator_feedback_events(run_id, recorded_at DESC);

CREATE INDEX idx_finding_status_events_run_time ON finding_status_events(run_id, recorded_at DESC);

CREATE INDEX idx_finding_cases_source ON finding_cases(source_kind, source_id, source_finding_key);

CREATE INDEX idx_evidence_audit_tags_run_time ON evidence_audit_tag_events(run_id, recorded_at DESC);

CREATE INDEX idx_audit_events_created_at ON audit_events(created_at DESC);

CREATE INDEX idx_latest_payloads_updated_at ON latest_payloads(updated_at DESC);

CREATE INDEX idx_data_connections_updated_at ON data_connections(updated_at DESC);

CREATE INDEX idx_data_connections_polling_updated ON data_connections(polling_enabled, updated_at DESC);

CREATE INDEX idx_auth_users_role_active ON auth_users(role, is_active);

CREATE INDEX idx_auth_sessions_email ON auth_sessions(email, expires_at DESC);

CREATE INDEX idx_auth_sessions_revoked ON auth_sessions(revoked_at, expires_at DESC);

CREATE UNIQUE INDEX uq_auth_sessions_active_email ON auth_sessions(email) WHERE revoked_at IS NULL;

CREATE INDEX idx_telemetry_mappings_system_enabled
                ON telemetry_signal_mappings (system_id, enabled, source_tag);

CREATE INDEX idx_telemetry_mappings_system_canonical
                ON telemetry_signal_mappings (system_id, canonical_signal);

CREATE INDEX idx_normalized_telemetry_system_time
                ON normalized_telemetry (system_id, telemetry_timestamp DESC);

CREATE INDEX idx_normalized_telemetry_system_signal_time
                ON normalized_telemetry (system_id, canonical_signal, telemetry_timestamp DESC);

CREATE INDEX idx_normalized_telemetry_batch ON normalized_telemetry (batch_id);

CREATE INDEX idx_rejected_telemetry_batch ON rejected_telemetry (batch_id, rejection_id);

CREATE INDEX idx_rejected_telemetry_system_time
                ON rejected_telemetry (system_id, ingested_at DESC);

CREATE INDEX idx_telemetry_health_updated
                ON telemetry_ingestion_health (updated_at DESC);

CREATE INDEX idx_finding_cases_scope_created ON finding_cases(scope_storage_id, created_at DESC);

CREATE INDEX idx_finding_workflow_events_finding_version ON finding_workflow_events(finding_id, version DESC);

CREATE INDEX idx_evidence_runs_scope_created ON evidence_runs(scope_storage_id, created_at DESC, run_id DESC);

CREATE INDEX idx_live_config_scope_due
                ON live_analysis_configurations(scope_storage_id, enabled, next_analysis_at, system_id);

CREATE INDEX idx_live_runs_scope_created
                ON live_analysis_runs(scope_storage_id, created_at DESC, run_id DESC);

CREATE INDEX idx_live_analysis_runs_system_created
                ON live_analysis_runs(scope_storage_id, system_id, created_at DESC);

CREATE INDEX idx_live_analysis_runs_window
                ON live_analysis_runs(scope_storage_id, system_id, window_end DESC);

CREATE UNIQUE INDEX idx_live_analysis_one_running
                ON live_analysis_runs(scope_storage_id, system_id)
                WHERE status = 'running' AND scope_storage_id IS NOT NULL;

CREATE INDEX idx_live_findings_scope_observed
                ON live_findings(scope_storage_id, last_observed_at DESC, finding_id DESC);

CREATE INDEX idx_live_findings_system_state
                ON live_findings(scope_storage_id, system_id, current_state, last_observed_at DESC);

CREATE INDEX idx_live_findings_baseline_relationship
                ON live_findings(scope_storage_id, baseline_reference, relationship_identity);

CREATE INDEX idx_live_health_scope_system
                ON live_analysis_health(scope_storage_id, system_id);

CREATE INDEX idx_live_analysis_health_status
                ON live_analysis_health(scope_storage_id, current_status, updated_at DESC);

CREATE INDEX idx_validated_outcomes_latest
                ON validated_outcomes(
                    scope_storage_id, tenant_id, facility_id, system_id,
                    outcome_id, revision DESC
                );

CREATE INDEX idx_validated_outcomes_status_time
                ON validated_outcomes(
                    scope_storage_id, tenant_id, facility_id, system_id,
                    validation_status, occurred_start_at DESC
                );

CREATE INDEX idx_validated_outcomes_incident
                ON validated_outcomes(
                    scope_storage_id, tenant_id, facility_id, system_id,
                    canonical_incident_key, occurred_start_at DESC
                );

CREATE UNIQUE INDEX uq_validated_outcomes_source_identity
                ON validated_outcomes(
                    scope_storage_id, tenant_id, facility_id, system_id,
                    source_identity_hash
                ) WHERE source_identity_hash IS NOT NULL AND revision = 1;

CREATE UNIQUE INDEX uq_validated_outcomes_idempotency
                ON validated_outcomes(
                    scope_storage_id, tenant_id, facility_id, system_id,
                    idempotency_key
                ) WHERE idempotency_key IS NOT NULL;

CREATE INDEX idx_validated_outcome_links_latest
                ON validated_outcome_links(
                    scope_storage_id, tenant_id, facility_id, system_id,
                    link_id, revision DESC
                );

CREATE INDEX idx_validated_outcome_links_outcome
                ON validated_outcome_links(
                    scope_storage_id, tenant_id, facility_id, system_id,
                    outcome_id, outcome_revision_id
                );

CREATE INDEX idx_validated_outcome_links_subject
                ON validated_outcome_links(
                    scope_storage_id, tenant_id, facility_id, system_id,
                    subject_type, subject_id, context_fingerprint, compatibility_epoch
                );

CREATE INDEX idx_validated_outcome_links_lineage
                ON validated_outcome_links(finding_id, evidence_run_id, evidence_content_hash);

CREATE UNIQUE INDEX uq_validated_outcome_links_idempotency
                ON validated_outcome_links(
                    scope_storage_id, tenant_id, facility_id, system_id,
                    idempotency_key
                ) WHERE idempotency_key IS NOT NULL;

CREATE INDEX idx_health_relevance_versions_latest
                ON health_relevance_versions(
                    scope_storage_id, tenant_id, facility_id, system_id,
                    subject_type, subject_id, context_fingerprint,
                    compatibility_epoch, method_class, version DESC
                );

CREATE INDEX idx_health_relevance_versions_snapshot
                ON health_relevance_versions(input_snapshot_id, input_manifest_hash, method_class);

CREATE UNIQUE INDEX uq_health_relevance_versions_input
                ON health_relevance_versions(
                    state_key_hash, input_snapshot_id, input_manifest_hash,
                    method_class, method_version, configuration_hash, code_build_version
                );

CREATE INDEX idx_health_relevance_contributions_version
                ON health_relevance_contributions(relevance_version_id, evidence_treatment);

CREATE INDEX idx_health_relevance_contributions_outcome
                ON health_relevance_contributions(
                    scope_storage_id, tenant_id, facility_id, system_id,
                    outcome_id, outcome_revision_id
                );

CREATE INDEX idx_health_relevance_contributions_link
                ON health_relevance_contributions(
                    scope_storage_id, tenant_id, facility_id, system_id,
                    link_id, link_revision_id
                );

CREATE TRIGGER trg_data_connections_state_insert BEFORE INSERT ON data_connections FOR EACH ROW WHEN (NEW.status NOT IN ('offline', 'polling', 'online', 'ready', 'error', 'not_configured')
              OR NEW.polling_enabled NOT IN (0, 1)) EXECUTE FUNCTION reject_runtime_mutation('data_connection_state');

CREATE TRIGGER trg_data_connections_state_update BEFORE UPDATE OF status, polling_enabled ON data_connections FOR EACH ROW WHEN (NEW.status NOT IN ('offline', 'polling', 'online', 'ready', 'error', 'not_configured')
              OR NEW.polling_enabled NOT IN (0, 1)) EXECUTE FUNCTION reject_runtime_mutation('data_connection_state');

CREATE TRIGGER trg_runtime_auth_role_insert BEFORE INSERT ON auth_users FOR EACH ROW WHEN (NEW.role NOT IN ('viewer', 'operator', 'admin')) EXECUTE FUNCTION reject_runtime_mutation('auth_role');

CREATE TRIGGER trg_runtime_auth_role_update BEFORE UPDATE OF role ON auth_users FOR EACH ROW WHEN (NEW.role NOT IN ('viewer', 'operator', 'admin')) EXECUTE FUNCTION reject_runtime_mutation('auth_role');

CREATE TRIGGER trg_upload_jobs_json_insert BEFORE INSERT ON upload_jobs FOR EACH ROW WHEN (NOT (NEW.payload_json::json IS NOT NULL)) EXECUTE FUNCTION reject_runtime_mutation('invalid_json');

CREATE TRIGGER trg_upload_jobs_json_update BEFORE UPDATE OF payload_json ON upload_jobs FOR EACH ROW WHEN (NOT (NEW.payload_json::json IS NOT NULL)) EXECUTE FUNCTION reject_runtime_mutation('invalid_json');

CREATE TRIGGER trg_evidence_runs_json_insert BEFORE INSERT ON evidence_runs FOR EACH ROW WHEN (NOT (NEW.payload_json::json IS NOT NULL)) EXECUTE FUNCTION reject_runtime_mutation('invalid_json');

CREATE TRIGGER trg_evidence_runs_json_update BEFORE UPDATE OF payload_json ON evidence_runs FOR EACH ROW WHEN (NOT (NEW.payload_json::json IS NOT NULL)) EXECUTE FUNCTION reject_runtime_mutation('invalid_json');

CREATE TRIGGER trg_audit_events_json_insert BEFORE INSERT ON audit_events FOR EACH ROW WHEN (NOT (NEW.detail_json::json IS NOT NULL)) EXECUTE FUNCTION reject_runtime_mutation('invalid_json');

CREATE TRIGGER trg_audit_events_json_update BEFORE UPDATE OF detail_json ON audit_events FOR EACH ROW WHEN (NOT (NEW.detail_json::json IS NOT NULL)) EXECUTE FUNCTION reject_runtime_mutation('invalid_json');

CREATE TRIGGER trg_latest_payloads_json_insert BEFORE INSERT ON latest_payloads FOR EACH ROW WHEN (NOT (NEW.payload_json::json IS NOT NULL)) EXECUTE FUNCTION reject_runtime_mutation('invalid_json');

CREATE TRIGGER trg_latest_payloads_json_update BEFORE UPDATE OF payload_json ON latest_payloads FOR EACH ROW WHEN (NOT (NEW.payload_json::json IS NOT NULL)) EXECUTE FUNCTION reject_runtime_mutation('invalid_json');

CREATE TRIGGER trg_data_connections_json_insert BEFORE INSERT ON data_connections FOR EACH ROW WHEN (NOT (NEW.payload_json::json IS NOT NULL)) EXECUTE FUNCTION reject_runtime_mutation('invalid_json');

CREATE TRIGGER trg_data_connections_json_update BEFORE UPDATE OF payload_json ON data_connections FOR EACH ROW WHEN (NOT (NEW.payload_json::json IS NOT NULL)) EXECUTE FUNCTION reject_runtime_mutation('invalid_json');

CREATE TRIGGER trg_finding_cases_source_immutable BEFORE UPDATE OF source_kind, source_id, source_finding_key, scope_storage_id,
                             dataset_scope_json, source_snapshot_json ON finding_cases FOR EACH ROW EXECUTE FUNCTION reject_runtime_mutation('finding_case_source_immutable');

CREATE TRIGGER trg_finding_cases_no_delete BEFORE DELETE ON finding_cases FOR EACH ROW EXECUTE FUNCTION reject_runtime_mutation('finding_cases_preserve_identity');

CREATE TRIGGER trg_finding_workflow_events_no_update BEFORE UPDATE ON finding_workflow_events FOR EACH ROW EXECUTE FUNCTION reject_runtime_mutation('finding_workflow_events_append_only');

CREATE TRIGGER trg_finding_workflow_events_no_delete BEFORE DELETE ON finding_workflow_events FOR EACH ROW EXECUTE FUNCTION reject_runtime_mutation('finding_workflow_events_append_only');

CREATE TRIGGER trg_validated_outcomes_no_update BEFORE UPDATE ON validated_outcomes FOR EACH ROW EXECUTE FUNCTION reject_runtime_mutation('validated_outcomes_append_only');

CREATE TRIGGER trg_validated_outcomes_no_delete BEFORE DELETE ON validated_outcomes FOR EACH ROW EXECUTE FUNCTION reject_runtime_mutation('validated_outcomes_append_only');

CREATE TRIGGER trg_validated_outcome_links_no_update BEFORE UPDATE ON validated_outcome_links FOR EACH ROW EXECUTE FUNCTION reject_runtime_mutation('validated_outcome_links_append_only');

CREATE TRIGGER trg_validated_outcome_links_no_delete BEFORE DELETE ON validated_outcome_links FOR EACH ROW EXECUTE FUNCTION reject_runtime_mutation('validated_outcome_links_append_only');

CREATE TRIGGER trg_health_relevance_versions_no_update BEFORE UPDATE ON health_relevance_versions FOR EACH ROW EXECUTE FUNCTION reject_runtime_mutation('health_relevance_versions_append_only');

CREATE TRIGGER trg_health_relevance_versions_no_delete BEFORE DELETE ON health_relevance_versions FOR EACH ROW EXECUTE FUNCTION reject_runtime_mutation('health_relevance_versions_append_only');

CREATE TRIGGER trg_health_relevance_contributions_no_update BEFORE UPDATE ON health_relevance_contributions FOR EACH ROW EXECUTE FUNCTION reject_runtime_mutation('health_relevance_contributions_append_only');

CREATE TRIGGER trg_health_relevance_contributions_no_delete BEFORE DELETE ON health_relevance_contributions FOR EACH ROW EXECUTE FUNCTION reject_runtime_mutation('health_relevance_contributions_append_only');
