#!/usr/bin/env python3
"""Render retrospective results from saved assessment only."""
import json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1];OUT=ROOT/'docs/validation/wastewater-real-2026';RAW=OUT/'raw'
def load(n):return json.loads((RAW/n).read_text())
def main():
 a=load('assessment.json');c=a['counts'];q=load('qualification.json');d=load('quality-details.json');ex=load('execution.json');rep=load('repeatability.json');freeze=load('freeze.json')
 rows=['# Wastewater retrospective validation report','',f"Engine commit: `{freeze['commit']}`. Source SHA-256: `{freeze['source_sha256']}`.",'','Production analytical logic, thresholds, baseline rules, persistence, recurrence, governance and operating-context rules were unchanged. All results below come from the frozen chronological run; external contextualization is separate. See METHODOLOGY.md, DATASET_PROVENANCE.md and LIMITATIONS.md.','','## Exact accounting','','Metric | Count','--- | ---']
 rows += [f"{k.replace('_',' ')} | {v}" for k,v in c.items()]
 rows += ['',f"Source span: {d['source_span_days']} days, {q['start']} through {q['end']}, unspecified source clock. The 2,015 retained reference rows precede every comparison; unique rows are counted once. Counts of evaluated pair-windows repeat the same relationship over time.",'','## Result status and qualification','']
 for key in ['window_status','limited_modules','temporal_status','change_types','insight_categories','consequence_status','pair_window_context','pair_window_quality']:
  rows += [f"**{key.replace('_',' ')}**",'', '```json',json.dumps(a[key],indent=2),'```','']
 rows += ['Insufficient-evidence insight classifications are counted above exactly as emitted. Unconfirmed graph persistence and context-limited insights are separately reported; neither is silently relabeled a confirmed transient. Changed-without-support counts use engine change_type excluding stable/unchanged and no temporal or recurrence support. Graph promotion and governed persistence counts are not interchangeable with temporal support.','', '## Per-relationship evidence','','Relationship | Evaluations | Temporal supported windows | Recurrence supported windows | Governed persistent windows | First temporal support (source clock)','--- | ---: | ---: | ---: | ---: | ---']
 for p in a['pairs']:rows.append(f"{p['pair']} | {p['evaluations']} | {p['temporal']['pair_windows']} | {p['recurrence']['pair_windows']} | {p['governed']['pair_windows']} | {p['temporal']['first_support_time'] or 'None'}")
 rows += ['','Full runs, first/last support times and correlation ranges are in FINDINGS.md and raw/assessment.json; raw/edge-results.jsonl retains every pair-window evidence projection and links to full checkpoints. All governed insight records are in raw/insights.jsonl.','','## Data quality','','Variable | Finite cells | Invalid cells | Minimum | Maximum | Zero cells','--- | ---: | ---: | ---: | ---: | ---:']
 for s,v in q['signals'].items():rows.append(f"{s} | {v['finite']} | {len(v['invalid_rows'])} | {v['min']} | {v['max']} | {v['zero_count']}")
 rows += ['',f"One source flow cell is `???` (data row 54). Existing complete-case governance excludes that row. There are {len(d['negative_flow_rows'])} negative finite flow readings, retained unchanged. Six gaps account for {d['absent_five_minute_slots']} absent five-minute slots relative to a continuous grid. They are not manufactured or interpolated.",'','Gap start | Gap end | Seconds | Absent 5-minute slots','--- | --- | ---: | ---:']
 rows += [f"{g['before']} | {g['after']} | {g['seconds']} | {g['absent_five_minute_slots']}" for g in d['gaps']]
 rows += ['','Longest constant string-valued source stretches (descriptive audit, not added exclusions):','','Variable | Rows | Value | Start | End','--- | ---: | --- | --- | ---']
 for s,v in d['constant_string_run_audit'].items():
  x=v['longest']
  if x:rows.append(f"{s} | {x['rows']} | {x['value']} | {x['start_time']} | {x['end_time']}")
 rows += ['','## Integrity, repeatability and performance','',f"The primary chronological replay took {ex['wall_seconds']:.3f} seconds including checkpoint serialization. It used one engine process with OPENBLAS_NUM_THREADS=1, OMP_NUM_THREADS=1 and PYTHONHASHSEED=0. Python/platform/packages: raw/freeze.json; CPU details: raw/hardware.txt. This is a shared-machine observation, not a benchmark guarantee.",'',f"Input hashes were independently reconstructed for {rep['checked_input_hash_windows']} windows. All numeric cells and source order were verified unchanged by normalization. Source and production hashes were verified unchanged. Checkpoint predecessor links, state handoff, row nonoverlap and chronology were checked. Fresh-process repeats matched {sum(x['equal'] for x in rep['repeats'])}/{len(rep['repeats'])} selected windows (first, middle, last). Scope: {rep['repeat_scope']}",'','The primary run log retains numerical runtime warnings. The supplementary descriptive audit initially failed to parse the nonnumeric flow cell; the audit was corrected to handle it, with no change to engine execution or inclusion policy. This development failure is retained in raw/quality-details.json. Production outputs were not repaired or tuned.','','## Reproduction and evidence map','','Follow METHODOLOGY.md. Exact commands: raw/commands.json. Initial freeze: raw/freeze.json. Prespecified protocol/configuration: raw/protocol.json and raw/config.json. Output freeze: raw/analytical-output-freeze.json. Full engine results and chained state provenance: raw/checkpoints/*.json. Input: raw/normalized.csv, indexed by the checkpoint source row lists. Source quality and exclusions: raw/qualification.json, raw/quality-view.json and raw/quality-details.json. Derived counts: raw/assessment.json. Verification: raw/repeatability.json and raw/final-verification.json.','','No accuracy, sensitivity, specificity, false-positive rate, physical loss, emission reduction or economic benefit is inferred. External source matching and event context are discussed only in POSTHOC_CONTEXT.md.']
 (OUT/'VALIDATION_REPORT.md').write_text('\n'.join(rows)+'\n')
 f=['# Retrospective relationship findings','','These are engine-emitted temporal/recurrence support observations, subject to governance and context limitations. They are not independently confirmed plant events. Full promoted and governed counts are in VALIDATION_REPORT.md.','','## All supported observation runs','','Relationship | Channel | First window | Last window | Supported windows | First support time | Last support time | Span days | Reference correlation | Current correlation range','--- | --- | ---: | ---: | ---: | --- | --- | ---: | ---: | ---']
 for p in a['pairs']:
  for channel in ['temporal','recurrence','governed','promoted']:
   for r in p[channel]['runs']:f.append(f"{p['pair']} | {channel} | {r['first_window']} | {r['last_window']} | {r['windows']} | {r['first_support_time']} | {r['last_support_time']} | {r['support_observation_span_days']:.6f} | {r['baseline_correlation']} | {r['current_correlation_min']} to {r['current_correlation_max']}")
 f += ['','Window indices are zero-based. First support is the completion time of the first engine-supported window, not estimated onset. Span is last minus first supported completion time; a single supported observation has zero span. Supporting-window provenance inside checkpoints may start before promotion. Gaps and unqualified intervening windows do not count as uninterrupted support. Correlations are dimensionless; no physical magnitude, emissions burden, cost or benefit is assigned.','','## Strongest sustained temporal evidence','','Ranked descriptively by longest consecutive run of temporal-supported windows; this is reporting, not a new qualification rule.']
 ranked=sorted([(r['windows'],p['pair'],r) for p in a['pairs'] for r in p['temporal']['runs']],key=lambda x:(-x[0],x[1]))
 for n,p,r in ranked[:5]:f.append(f"\n- {p}: {n} consecutive supported daily evaluations, {r['first_support_time']} to {r['last_support_time']}; {r['support_observation_span_days']:.3f}-day supported-observation span. Reference correlation {r['baseline_correlation']}; current correlations {r['current_correlation_min']} to {r['current_correlation_max']}.")
 (OUT/'FINDINGS.md').write_text('\n'.join(f)+'\n')
if __name__=='__main__':main()
