#!/usr/bin/env python3
import json,collections
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1];OUT=ROOT/'docs/validation/wastewater-real-2026';RAW=OUT/'raw'
a=json.loads((RAW/'assessment.json').read_text());edges=[json.loads(x) for x in (RAW/'edge-results.jsonl').open()];counts=collections.Counter();governed=[]
for e in edges:
 t=bool(e['temporal_persistence_supported']);r=bool(e['recurrence_evidence']['supported']);counts[f'temporal_{t}_recurrence_{r}']+=1
 if e['governed_persistent']:governed.append(e)
extra={'mutually_exclusive_graph_support_counts':dict(counts),'possible_pair_windows':21*253,'returned_pair_windows':len(edges),'omitted_pair_windows':21*253-len(edges),'omitted_reason':'Eight windows have constant NH4 and omit its six correlations; see omitted-pairs.json. These are not stable negative results.','governed_records':governed}
(RAW/'support-accounting.json').write_text(json.dumps(extra,indent=2)+'\n')
f=['## Promoted and governed persistent evidence','','Only the following four pair-window observations passed graph promotion and retained governed persistent relationship flags. They cover two distinct relationships; they are not four independently verified plant events. All remained context-limited.','','Pair | Window | First governed support at window completion | Reference r | Current r | Absolute delta r | Retained supporting observation interval','--- | ---: | --- | ---: | ---: | ---: | ---']
for e in governed:f.append(f"{' / '.join(e['columns'])} | {e['window']} | {e['end']} | {e['baseline_correlation']} | {e['current_correlation']} | {e['absolute_correlation_delta']} | {e['first_supported_observation']} to {e['latest_supported_observation']}")
f+=['','Each governed appearance is isolated in consecutive promotion bookkeeping (zero first-to-last promotion span), while its engine-retained support spans several preceding observations. NH4/NO3 first qualifies on 2018-11-28; NO3/N2O first qualifies on 2019-02-13 and reappears on 2019-02-25 and 2019-02-28. Reappearance is not automatically the separate recurrence endpoint. The last appearance follows a source gap, so no continuous physical-duration claim is made.','']
p=OUT/'FINDINGS.md';s=p.read_text();s=s.replace('## All supported observation runs','\n'.join(f)+'\n## All supported observation runs');p.write_text(s)
p=OUT/'VALIDATION_REPORT.md';s=p.read_text();s+='\n## Additional evidence sufficiency accounting\n\nOf 5,313 possible pair-window slots, 5,265 contain graph edges. The 48 absent slots are the six NH4 relationships in eight windows with constant NH4. They are unavailable correlations, not stable controls. The relationship-analysis module still reports complete in those windows; read coverage alongside status. See raw/omitted-pairs.json.\n\nMutually exclusive support categories (distinct from change-type categories):\n\n```json\n'+json.dumps(dict(counts),indent=2)+'\n```\n\nGraph support channels can overlap. There are 46 insufficient-evidence insight observations and 1,149 context-limited insight observations, not deduplicated incidents. No measurable consequence was quantifiable in any of the 1,195 insights. Read the promoted/governed table at the start of FINDINGS.md before the broader temporal-support runs.\n';p.write_text(s)
